services:
  mysql_db:
    image: mysql:8.0
    container_name: wcf_mysql
    restart: always
    env_file:
      - ./.env
    volumes:
      - wcf_data_volume:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - net

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  php_site:
    build: .
    restart: always
    container_name: wcf_php
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    networks:
      - net
    volumes:
      - .:/var/www/html/
    depends_on:
      mysql_db:
        condition: service_healthy
    tty: true

    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s 

  nginx_site:
    image: nginx:stable-alpine
    container_name: wcf_nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - net
    depends_on:
      php_site:
        condition: service_healthy

volumes:
  wcf_data_volume:

networks:
  net:
    driver: bridge